/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package workshop.iplanalysis;

public class WelcomeMessage {
   public static void main(String args[])
   {
	   System.out.println("Welcome to IPL League Analyzer.");
   }
}
